apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: laravel

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:8.0

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              value: demoproject

            - name: MYSQL_USER
              value: laravel

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secret
                  key: DB_PASSWORD

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secret
                  key: MYSQL_ROOT_PASSWORD

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
