apiVersion: v1
kind: Secret

metadata:
  name: laravel-secret
  namespace: laravel

type: Opaque

stringData:
  APP_KEY: "base64:LqoJgAjnGPeRKNiQwdeqM01LRlhEkznXn5KQ6myWmLg="
  DB_PASSWORD: "root"
  MYSQL_ROOT_PASSWORD: "root"
